// Generated by CoffeeScript 1.9.1
var helpers, moment;

moment = require('timespanner');

helpers = require('odoql-utils/helpers');

module.exports = {
  unary: {
    time: function(exe, params) {
      return helpers.unary(exe, params, function(source) {
        return moment.spanner(source);
      });
    }
  }
};
